# Generated by Django 3.1.3 on 2020-11-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('servicio', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=6)),
            ],
        ),
    ]
